# Data Structures
## User (object)
+ id: hogehoge001 (string, required) - ユーザID
+ name: nickname (string, required) - 名前
+ profile: プロフィール (string, required) - プロフィール
+ user_url: https://example.com (string) - URLリンク
+ email: example@hoge.com (string, required) - メールアドレス
+ password: password01 (string, required) - パスワード
+ theme_color: #ffffff (string) - テーマカラー16進数

## success (object)
+ result: Success (string, required) - 結果
+ detail: (object, required) - 詳細

## clientError (object)
+ result: Error (string, required) - 結果
+ message: Bad Request (string, required) - 詳細メッセージ

## posting (object)
+ id: kfiue89cew (string, required) - post_id 
+ detail: ラーメン食べたい (string, required) - 投稿文章
+ image_id: fugefuge (string) - 投稿画像ファイル名
+ user_id: hogehoge001 (string, required) - 投稿者ID
+ post_datetime: `2021-09-25 12:00:00:01` (string, required) - 投稿日時