FORMAT: 1A
<!-- include(datastructure.apib) -->
HOST: https://example.com/api/v1

# follow

## フォロー [POST /follow/:id]

## アンフォロー [DELETE /unfollow/:id]

## フォローリスト [GET /follow_list/:id]

## フォロワーリスト [GET /follower_list/:id]