FORMAT: 1A
HOST: https://example.com/api/v1

# SNS API
就職作品のSNSのAPI

## フォロー [POST /follow/:id]

## アンフォロー [DELETE /unfollow/:id]

## フォローリスト [GET /follow_list/:id]

## フォロワーリスト [GET /follower_list/:id]