FORMAT: 1A
HOST: https://app/api/v1

# SNS API
就職作品のSNSのAPI

## ユーザ登録 [POST /user]
+ Request (application/json)
  + Attributes

+ Response 200 (application/json)

## ユーザ情報変更 [PUT /user]
+ Request (application/json)

## ユーザ情報取得 [GET /user]

## ユーザ削除 [DELETE /user]

## トークン発行 [POST /token]

## プロフィール取得 [GET /profile/:id]

## 投稿 [POST /post]

## 投稿内容 [GET /post/:id]

## 投稿編集 [PUT /post/:id]

## 投稿削除 [DELETE /post/:id]

## 投稿一覧 [GET /posts/:id]

## フォロー [POST /follow/:id]

## アンフォロー [DELETE /unfollow/:id]

## フォローリスト [GET /follow_list/:id]

## フォロワーリスト [GET /follower_list/:id]