FORMAT: 1A
HOST: https://app/api/v1

# SNS API
就職作品のSNSのAPI

## ユーザ登録 [POST /user]
+ Request (application/json)
  + Attributes

+ Response 200 (application/json)

## ユーザ情報変更 [PUT /user]
+ Request (application/json)

## ユーザ情報取得 [GET /user]

## ユーザ削除 [DELETE /user]

## トークン発行 [POST /token]

## プロフィール取得 [GET /profile/:id]

## 投稿 [POST /show]